// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/19/2025, 4:19:56 PM
const configMerger = require("/Users/maaswick/Documents/work/nxlandz/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/maaswick/Documents/work/nxlandz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/plugins/**/*.{js,ts,mjs}","/Users/maaswick/Documents/work/nxlandz/composables/**/*.{js,ts,mjs}","/Users/maaswick/Documents/work/nxlandz/utils/**/*.{js,ts,mjs}","/Users/maaswick/Documents/work/nxlandz/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maaswick/Documents/work/nxlandz/app.config.{js,ts,mjs}"] }));

module.exports = config
